openapi: 3.0.1
info:
  description: ""
  title: Deals
  version: v3
  x-hubspot-product-tier-requirements:
    marketing: FREE
    sales: FREE
    service: FREE
    cms: FREE
  x-hubspot-documentation-banner: NONE
  x-hubspot-api-use-case: "When a sales rep is negotiating a potential purchase with\
    \ a prospective customer, create a deal record to track the negotiation process.\
    \ When the customer later makes their purchase, you can update the deal to a closed\
    \ stage."
  x-hubspot-related-documentation:
  - name: Deals Guide
    url: https://hubspot.dev/guides/api/crm/deals
  x-hubspot-introduction: "Use the deals API to create and manage CRM records that\
    \ represent transactions with contacts and/or companies. Deals progress through\
    \ pipeline stages to reflect whether the transaction has been completed, is active,\
    \ or has otherwise been lost."
servers:
- url: https://api.hubapi.com
tags:
- name: Batch
- name: Basic
- name: Public_Object
- name: Associations
- name: GDPR
- name: Search
paths:
  /crm/v3/objects/deals/batch/read:
    post:
      operationId: BatchRead
      parameters:
      - description: Whether to return only results that have been archived.
        explode: true
        in: query
        name: archived
        required: false
        schema:
          default: false
          type: boolean
        style: form
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BatchReadInputSimplePublicObjectId'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BatchResponseSimplePublicObject'
          description: successful operation
        "207":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BatchResponseSimplePublicObjectWithErrors'
          description: multiple statuses
        default:
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Error'
          description: An error occurred.
      security:
      - oauth2:
        - crm.objects.deals.read
      - private_apps:
        - crm.objects.deals.read
      summary: "Read a batch of deals by internal ID, or unique property values"
      tags:
      - Batch
  /crm/v3/objects/deals/{dealId}:
    delete:
      description: "Move an Object identified by `{dealId}` to the recycling bin."
      operationId: Archive
      parameters:
      - explode: false
        in: path
        name: dealId
        required: true
        schema:
          type: string
        style: simple
      responses:
        "204":
          content: {}
          description: No content
        default:
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Error'
          description: An error occurred.
      security:
      - oauth2:
        - crm.objects.deals.write
      - private_apps:
        - crm.objects.deals.write
      summary: Archive
      tags:
      - Basic
    get:
      description: "Read an Object identified by `{dealId}`. `{dealId}` refers to\
        \ the internal object ID by default, or optionally any unique property value\
        \ as specified by the `idProperty` query param.  Control what is returned\
        \ via the `properties` query param."
      operationId: GetByID
      parameters:
      - explode: false
        in: path
        name: dealId
        required: true
        schema:
          type: string
        style: simple
      - description: "A comma separated list of the properties to be returned in the\
          \ response. If any of the specified properties are not present on the requested\
          \ object(s), they will be ignored."
        explode: true
        in: query
        name: properties
        required: false
        schema:
          items:
            type: string
          type: array
        style: form
      - description: "A comma separated list of the properties to be returned along\
          \ with their history of previous values. If any of the specified properties\
          \ are not present on the requested object(s), they will be ignored."
        explode: true
        in: query
        name: propertiesWithHistory
        required: false
        schema:
          items:
            type: string
          type: array
        style: form
      - description: "A comma separated list of object types to retrieve associated\
          \ IDs for. If any of the specified associations do not exist, they will\
          \ be ignored."
        explode: true
        in: query
        name: associations
        required: false
        schema:
          items:
            type: string
          type: array
        style: form
      - description: Whether to return only results that have been archived.
        explode: true
        in: query
        name: archived
        required: false
        schema:
          default: false
          type: boolean
        style: form
      - description: The name of a property whose values are unique for this object
          type
        explode: true
        in: query
        name: idProperty
        required: false
        schema:
          type: string
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SimplePublicObjectWithAssociations'
          description: successful operation
        default:
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Error'
          description: An error occurred.
      security:
      - oauth2:
        - crm.objects.deals.read
      - private_apps:
        - crm.objects.deals.read
      summary: Read
      tags:
      - Basic
    patch:
      description: "Perform a partial update of an Object identified by `{dealId}`.\
        \ `{dealId}` refers to the internal object ID by default, or optionally any\
        \ unique property value as specified by the `idProperty` query param. Provided\
        \ property values will be overwritten. Read-only and non-existent properties\
        \ will be ignored. Properties values can be cleared by passing an empty string."
      operationId: Update
      parameters:
      - explode: false
        in: path
        name: dealId
        required: true
        schema:
          type: string
        style: simple
      - description: The name of a property whose values are unique for this object
          type
        explode: true
        in: query
        name: idProperty
        required: false
        schema:
          type: string
        style: form
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SimplePublicObjectInput'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SimplePublicObject'
          description: successful operation
        default:
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Error'
          description: An error occurred.
      security:
      - oauth2:
        - crm.objects.deals.write
      - private_apps:
        - crm.objects.deals.write
      summary: Update
      tags:
      - Basic
  /crm/v3/objects/deals/merge:
    post:
      operationId: Merge
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PublicMergeInput'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SimplePublicObject'
          description: successful operation
        default:
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Error'
          description: An error occurred.
      security:
      - oauth2:
        - crm.objects.deals.write
      - private_apps:
        - crm.objects.deals.write
      summary: Merge two deals with same type
      tags:
      - Public_Object
  /crm/v3/objects/deals/batch/archive:
    post:
      operationId: BatchArchive
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BatchInputSimplePublicObjectId'
        required: true
      responses:
        "204":
          content: {}
          description: No content
        default:
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Error'
          description: An error occurred.
      security:
      - oauth2:
        - crm.objects.deals.write
      - private_apps:
        - crm.objects.deals.write
      summary: Archive a batch of deals by ID
      tags:
      - Batch
  /crm/v3/objects/deals/batch/create:
    post:
      operationId: BatchCreate
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BatchInputSimplePublicObjectInputForCreate'
        required: true
      responses:
        "201":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BatchResponseSimplePublicObject'
          description: successful operation
        "207":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BatchResponseSimplePublicObjectWithErrors'
          description: multiple statuses
        default:
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Error'
          description: An error occurred.
      security:
      - oauth2:
        - crm.objects.deals.write
      - private_apps:
        - crm.objects.deals.write
      summary: Create a batch of deals
      tags:
      - Batch
  /crm/v3/objects/deals/batch/update:
    post:
      operationId: BatchUpdate
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BatchInputSimplePublicObjectBatchInput'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BatchResponseSimplePublicObject'
          description: successful operation
        "207":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BatchResponseSimplePublicObjectWithErrors'
          description: multiple statuses
        default:
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Error'
          description: An error occurred.
      security:
      - oauth2:
        - crm.objects.deals.write
      - private_apps:
        - crm.objects.deals.write
      summary: Update a batch of deals
      tags:
      - Batch
  /crm/v3/objects/deals/gdpr-delete:
    post:
      description: "Permanently delete a contact and all associated content to follow\
        \ GDPR. Use optional property 'idProperty' set to 'email' to identify contact\
        \ by email address. If email address is not found, the email address will\
        \ be added to a blocklist and prevent it from being used in the future."
      operationId: post-/crm/v3/objects/deals/gdpr-delete_purge
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PublicGdprDeleteInput'
        required: true
      responses:
        "204":
          content: {}
          description: No content
        default:
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Error'
          description: An error occurred.
      security:
      - oauth2:
        - crm.objects.deals.write
      - private_apps:
        - crm.objects.deals.write
      summary: GDPR DELETE
      tags:
      - GDPR
  /crm/v3/objects/deals:
    get:
      description: Read a page of deals. Control what is returned via the `properties`
        query param.
      operationId: GetPage
      parameters:
      - description: The maximum number of results to display per page.
        explode: true
        in: query
        name: limit
        required: false
        schema:
          default: 10
          format: int32
          type: integer
        style: form
      - description: The paging cursor token of the last successfully read resource
          will be returned as the `paging.next.after` JSON property of a paged response
          containing more results.
        explode: true
        in: query
        name: after
        required: false
        schema:
          type: string
        style: form
      - description: "A comma separated list of the properties to be returned in the\
          \ response. If any of the specified properties are not present on the requested\
          \ object(s), they will be ignored."
        explode: true
        in: query
        name: properties
        required: false
        schema:
          items:
            type: string
          type: array
        style: form
      - description: "A comma separated list of the properties to be returned along\
          \ with their history of previous values. If any of the specified properties\
          \ are not present on the requested object(s), they will be ignored. Usage\
          \ of this parameter will reduce the maximum number of objects that can be\
          \ read by a single request."
        explode: true
        in: query
        name: propertiesWithHistory
        required: false
        schema:
          items:
            type: string
          type: array
        style: form
      - description: "A comma separated list of object types to retrieve associated\
          \ IDs for. If any of the specified associations do not exist, they will\
          \ be ignored."
        explode: true
        in: query
        name: associations
        required: false
        schema:
          items:
            type: string
          type: array
        style: form
      - description: Whether to return only results that have been archived.
        explode: true
        in: query
        name: archived
        required: false
        schema:
          default: false
          type: boolean
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CollectionResponseSimplePublicObjectWithAssociationsForwardPaging'
          description: successful operation
        default:
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Error'
          description: An error occurred.
      security:
      - oauth2:
        - crm.objects.deals.read
      - private_apps:
        - crm.objects.deals.read
      summary: List
      tags:
      - Basic
    post:
      description: "Create a deal with the given properties and return a copy of the\
        \ object, including the ID. Documentation and examples for creating standard\
        \ deals is provided."
      operationId: Create
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SimplePublicObjectInputForCreate'
        required: true
      responses:
        "201":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SimplePublicObject'
          description: successful operation
        default:
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Error'
          description: An error occurred.
      security:
      - oauth2:
        - crm.objects.deals.write
      - private_apps:
        - crm.objects.deals.write
      summary: Create
      tags:
      - Basic
  /crm/v3/objects/deals/search:
    post:
      operationId: Search
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PublicObjectSearchRequest'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CollectionResponseWithTotalSimplePublicObjectForwardPaging'
          description: successful operation
        default:
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Error'
          description: An error occurred.
      security:
      - oauth2:
        - crm.objects.deals.read
      - private_apps:
        - crm.objects.deals.read
      tags:
      - Search
      x-hubspot-rate-limit-exemptions:
      - ten-secondly
components:
  responses:
    Error:
      content:
        '*/*':
          schema:
            $ref: '#/components/schemas/Error'
      description: An error occurred.
  schemas:
    StandardError:
      properties:
        subCategory:
          properties: {}
          type: object
        context:
          additionalProperties:
            items:
              type: string
            type: array
          type: object
        links:
          additionalProperties:
            type: string
          type: object
        id:
          type: string
        category:
          type: string
        message:
          type: string
        errors:
          items:
            $ref: '#/components/schemas/ErrorDetail'
          type: array
        status:
          type: string
      required:
      - category
      - context
      - errors
      - links
      - message
      - status
      type: object
    CollectionResponseAssociatedId:
      properties:
        paging:
          $ref: '#/components/schemas/Paging'
        results:
          items:
            $ref: '#/components/schemas/AssociatedId'
          type: array
      required:
      - results
      type: object
    PublicAssociationsForObject:
      properties:
        types:
          items:
            $ref: '#/components/schemas/AssociationSpec'
          type: array
        to:
          $ref: '#/components/schemas/PublicObjectId'
      required:
      - to
      - types
      type: object
    BatchResponseSimplePublicObject:
      example:
        completedAt: 2000-01-23T04:56:07.000+00:00
        requestedAt: 2000-01-23T04:56:07.000+00:00
        startedAt: 2000-01-23T04:56:07.000+00:00
        links:
          key: links
        results:
        - id: "512"
          properties:
            amount: "1500.00"
            closedate: 2019-12-07T16:50:06.678Z
            createdate: 2019-10-30T03:30:17.883Z
            dealname: Custom data integrations
            dealstage: presentationscheduled
            hs_lastmodifieddate: 2019-12-07T16:50:06.678Z
            hubspot_owner_id: "910901"
            pipeline: default
          createdAt: 2019-10-30T03:30:17.883Z
          updatedAt: 2019-12-07T16:50:06.678Z
          archived: false
        - id: "512"
          properties:
            amount: "1500.00"
            closedate: 2019-12-07T16:50:06.678Z
            createdate: 2019-10-30T03:30:17.883Z
            dealname: Custom data integrations
            dealstage: presentationscheduled
            hs_lastmodifieddate: 2019-12-07T16:50:06.678Z
            hubspot_owner_id: "910901"
            pipeline: default
          createdAt: 2019-10-30T03:30:17.883Z
          updatedAt: 2019-12-07T16:50:06.678Z
          archived: false
        status: PENDING
      properties:
        completedAt:
          format: date-time
          type: string
        requestedAt:
          format: date-time
          type: string
        startedAt:
          format: date-time
          type: string
        links:
          additionalProperties:
            type: string
          type: object
        results:
          items:
            $ref: '#/components/schemas/SimplePublicObject'
          type: array
        status:
          enum:
          - PENDING
          - PROCESSING
          - CANCELED
          - COMPLETE
          type: string
      required:
      - completedAt
      - results
      - startedAt
      - status
      type: object
    FilterGroup:
      example:
        filters:
        - highValue: highValue
          propertyName: propertyName
          values:
          - values
          - values
          value: value
          operator: EQ
        - highValue: highValue
          propertyName: propertyName
          values:
          - values
          - values
          value: value
          operator: EQ
      properties:
        filters:
          items:
            $ref: '#/components/schemas/Filter'
          type: array
      required:
      - filters
      type: object
    ErrorDetail:
      properties:
        subCategory:
          description: A specific category that contains more specific detail about
            the error
          type: string
        code:
          description: The status code associated with the error detail
          type: string
        in:
          description: The name of the field or parameter in which the error was found.
          type: string
        context:
          additionalProperties:
            items:
              type: string
            type: array
          description: Context about the error condition
          example:
            missingScopes:
            - scope1
            - scope2
          type: object
        message:
          description: A human readable message describing the error along with remediation
            steps where appropriate
          type: string
      required:
      - message
      type: object
    ForwardPaging:
      example:
        next:
          after: NTI1Cg%3D%3D
          link: ?after=NTI1Cg%3D%3D
      properties:
        next:
          $ref: '#/components/schemas/NextPage'
      type: object
    SimplePublicObjectId:
      example:
        id: id
      properties:
        id:
          type: string
      required:
      - id
      type: object
    BatchReadInputSimplePublicObjectId:
      example:
        propertiesWithHistory:
        - propertiesWithHistory
        - propertiesWithHistory
        idProperty: idProperty
        inputs:
        - id: id
        - id: id
        properties:
        - properties
        - properties
      properties:
        propertiesWithHistory:
          items:
            type: string
          type: array
        idProperty:
          type: string
        inputs:
          items:
            $ref: '#/components/schemas/SimplePublicObjectId'
          type: array
        properties:
          items:
            type: string
          type: array
      required:
      - inputs
      - properties
      - propertiesWithHistory
      type: object
    BatchInputSimplePublicObjectId:
      example:
        inputs:
        - id: id
        - id: id
      properties:
        inputs:
          items:
            $ref: '#/components/schemas/SimplePublicObjectId'
          type: array
      required:
      - inputs
      type: object
    ValueWithTimestamp:
      properties:
        sourceId:
          type: string
        sourceType:
          type: string
        sourceLabel:
          type: string
        updatedByUserId:
          format: int32
          type: integer
        value:
          type: string
        timestamp:
          format: date-time
          type: string
      required:
      - sourceType
      - timestamp
      - value
      type: object
    CollectionResponseWithTotalSimplePublicObjectForwardPaging:
      example:
        total: 0
        paging:
          next:
            after: NTI1Cg%3D%3D
            link: ?after=NTI1Cg%3D%3D
        results:
        - id: "512"
          properties:
            amount: "1500.00"
            closedate: 2019-12-07T16:50:06.678Z
            createdate: 2019-10-30T03:30:17.883Z
            dealname: Custom data integrations
            dealstage: presentationscheduled
            hs_lastmodifieddate: 2019-12-07T16:50:06.678Z
            hubspot_owner_id: "910901"
            pipeline: default
          createdAt: 2019-10-30T03:30:17.883Z
          updatedAt: 2019-12-07T16:50:06.678Z
          archived: false
        - id: "512"
          properties:
            amount: "1500.00"
            closedate: 2019-12-07T16:50:06.678Z
            createdate: 2019-10-30T03:30:17.883Z
            dealname: Custom data integrations
            dealstage: presentationscheduled
            hs_lastmodifieddate: 2019-12-07T16:50:06.678Z
            hubspot_owner_id: "910901"
            pipeline: default
          createdAt: 2019-10-30T03:30:17.883Z
          updatedAt: 2019-12-07T16:50:06.678Z
          archived: false
      properties:
        total:
          format: int32
          type: integer
        paging:
          $ref: '#/components/schemas/ForwardPaging'
        results:
          items:
            $ref: '#/components/schemas/SimplePublicObject'
          type: array
      required:
      - results
      - total
      type: object
    SimplePublicObject:
      example:
        id: "512"
        properties:
          amount: "1500.00"
          closedate: 2019-12-07T16:50:06.678Z
          createdate: 2019-10-30T03:30:17.883Z
          dealname: Custom data integrations
          dealstage: presentationscheduled
          hs_lastmodifieddate: 2019-12-07T16:50:06.678Z
          hubspot_owner_id: "910901"
          pipeline: default
        createdAt: 2019-10-30T03:30:17.883Z
        updatedAt: 2019-12-07T16:50:06.678Z
        archived: false
      properties:
        createdAt:
          format: date-time
          type: string
        archived:
          example: false
          type: boolean
        archivedAt:
          format: date-time
          type: string
        propertiesWithHistory:
          additionalProperties:
            items:
              $ref: '#/components/schemas/ValueWithTimestamp'
            type: array
          type: object
        id:
          example: "512"
          type: string
        properties:
          additionalProperties:
            nullable: true
            type: string
          example:
            property_date: "1572480000000"
            property_radio: option_1
            property_number: "17"
            property_string: value
            property_checkbox: "false"
            property_dropdown: choice_b
            property_multiple_checkboxes: chocolate;strawberry
          type: object
        updatedAt:
          format: date-time
          type: string
      required:
      - createdAt
      - id
      - properties
      - updatedAt
      type: object
    PublicObjectId:
      properties:
        id:
          type: string
      required:
      - id
      type: object
    Paging:
      properties:
        next:
          $ref: '#/components/schemas/NextPage'
        prev:
          $ref: '#/components/schemas/PreviousPage'
      type: object
    PublicObjectSearchRequest:
      example:
        query: query
        limit: 0
        after: after
        sorts:
        - sorts
        - sorts
        properties:
        - properties
        - properties
        filterGroups:
        - filters:
          - highValue: highValue
            propertyName: propertyName
            values:
            - values
            - values
            value: value
            operator: EQ
          - highValue: highValue
            propertyName: propertyName
            values:
            - values
            - values
            value: value
            operator: EQ
        - filters:
          - highValue: highValue
            propertyName: propertyName
            values:
            - values
            - values
            value: value
            operator: EQ
          - highValue: highValue
            propertyName: propertyName
            values:
            - values
            - values
            value: value
            operator: EQ
      properties:
        query:
          type: string
        limit:
          format: int32
          type: integer
        after:
          type: string
        sorts:
          items:
            type: string
          type: array
        properties:
          items:
            type: string
          type: array
        filterGroups:
          items:
            $ref: '#/components/schemas/FilterGroup'
          type: array
      required:
      - after
      - filterGroups
      - limit
      - properties
      - sorts
      type: object
    Error:
      example:
        message: Invalid input (details will vary based on the error)
        correlationId: aeb5f871-7f07-4993-9211-075dc63e7cbf
        category: VALIDATION_ERROR
        links:
          knowledge-base: https://www.hubspot.com/products/service/knowledge-base
      properties:
        subCategory:
          description: A specific category that contains more specific detail about
            the error
          type: string
        context:
          additionalProperties:
            items:
              type: string
            type: array
          description: Context about the error condition
          example:
            missingScopes:
            - scope1
            - scope2
            invalidPropertyName:
            - propertyValue
          type: object
        correlationId:
          description: A unique identifier for the request. Include this value with
            any error reports or support tickets
          example: aeb5f871-7f07-4993-9211-075dc63e7cbf
          format: uuid
          type: string
        links:
          additionalProperties:
            type: string
          description: A map of link names to associated URIs containing documentation
            about the error or recommended remediation steps
          example:
            knowledge-base: https://www.hubspot.com/products/service/knowledge-base
          type: object
        message:
          description: A human readable message describing the error along with remediation
            steps where appropriate
          example: Invalid input (details will vary based on the error)
          type: string
        category:
          description: The error category
          example: VALIDATION_ERROR
          type: string
        errors:
          description: further information about the error
          items:
            $ref: '#/components/schemas/ErrorDetail'
          type: array
      required:
      - category
      - correlationId
      - message
      type: object
    BatchResponseSimplePublicObjectWithErrors:
      properties:
        completedAt:
          format: date-time
          type: string
        numErrors:
          format: int32
          type: integer
        requestedAt:
          format: date-time
          type: string
        startedAt:
          format: date-time
          type: string
        links:
          additionalProperties:
            type: string
          type: object
        results:
          items:
            $ref: '#/components/schemas/SimplePublicObject'
          type: array
        errors:
          items:
            $ref: '#/components/schemas/StandardError'
          type: array
        status:
          enum:
          - PENDING
          - PROCESSING
          - CANCELED
          - COMPLETE
          type: string
      required:
      - completedAt
      - results
      - startedAt
      - status
      type: object
    PublicGdprDeleteInput:
      example:
        idProperty: idProperty
        objectId: objectId
      properties:
        idProperty:
          type: string
        objectId:
          type: string
      required:
      - objectId
      type: object
    SimplePublicObjectInput:
      example:
        properties:
          amount: "1500.00"
          dealname: Custom data integrations
          pipeline: default
          closedate: 2019-12-07T16:50:06.678Z
          dealstage: presentationscheduled
          hubspot_owner_id: "910901"
        associations:
        - to:
            id: "101"
          types:
          - associationCategory: HUBSPOT_DEFINED
            associationTypeId: 2
      properties:
        properties:
          additionalProperties:
            type: string
          example:
            property_date: "1572480000000"
            property_radio: option_1
            property_number: "17"
            property_string: value
            property_checkbox: "false"
            property_dropdown: choice_b
            property_multiple_checkboxes: chocolate;strawberry
          type: object
      required:
      - properties
      type: object
    CollectionResponseSimplePublicObjectWithAssociationsForwardPaging:
      example:
        paging:
          next:
            after: NTI1Cg%3D%3D
            link: ?after=NTI1Cg%3D%3D
        results:
        - properties:
            amount: "1500.00"
            closedate: 2019-12-07T16:50:06.678Z
            createdate: 2019-10-30T03:30:17.883Z
            dealname: Custom data integrations
            dealstage: presentationscheduled
            hs_lastmodifieddate: 2019-12-07T16:50:06.678Z
            hubspot_owner_id: "910901"
            pipeline: default
        - properties:
            amount: "1500.00"
            closedate: 2019-12-07T16:50:06.678Z
            createdate: 2019-10-30T03:30:17.883Z
            dealname: Custom data integrations
            dealstage: presentationscheduled
            hs_lastmodifieddate: 2019-12-07T16:50:06.678Z
            hubspot_owner_id: "910901"
            pipeline: default
      properties:
        paging:
          $ref: '#/components/schemas/ForwardPaging'
        results:
          items:
            $ref: '#/components/schemas/SimplePublicObjectWithAssociations'
          type: array
      required:
      - results
      type: object
    AssociationSpec:
      properties:
        associationCategory:
          enum:
          - HUBSPOT_DEFINED
          - USER_DEFINED
          - INTEGRATOR_DEFINED
          type: string
        associationTypeId:
          format: int32
          type: integer
      required:
      - associationCategory
      - associationTypeId
      type: object
    PublicMergeInput:
      example:
        objectIdToMerge: objectIdToMerge
        primaryObjectId: primaryObjectId
      properties:
        objectIdToMerge:
          type: string
        primaryObjectId:
          type: string
      required:
      - objectIdToMerge
      - primaryObjectId
      type: object
    SimplePublicObjectWithAssociations:
      example:
        properties:
          amount: "1500.00"
          closedate: 2019-12-07T16:50:06.678Z
          createdate: 2019-10-30T03:30:17.883Z
          dealname: Custom data integrations
          dealstage: presentationscheduled
          hs_lastmodifieddate: 2019-12-07T16:50:06.678Z
          hubspot_owner_id: "910901"
          pipeline: default
      properties:
        associations:
          additionalProperties:
            $ref: '#/components/schemas/CollectionResponseAssociatedId'
          type: object
        createdAt:
          format: date-time
          type: string
        archived:
          type: boolean
        archivedAt:
          format: date-time
          type: string
        propertiesWithHistory:
          additionalProperties:
            items:
              $ref: '#/components/schemas/ValueWithTimestamp'
            type: array
          type: object
        id:
          type: string
        properties:
          additionalProperties:
            nullable: true
            type: string
          example:
            amount: "1500.00"
            dealname: Custom data integrations
            pipeline: default
            closedate: 2019-12-07T16:50:06.678Z
            dealstage: presentationscheduled
            hubspot_owner_id: "910901"
          type: object
        updatedAt:
          format: date-time
          type: string
      required:
      - createdAt
      - id
      - properties
      - updatedAt
      type: object
    Filter:
      example:
        highValue: highValue
        propertyName: propertyName
        values:
        - values
        - values
        value: value
        operator: EQ
      properties:
        highValue:
          type: string
        propertyName:
          type: string
        values:
          items:
            type: string
          type: array
        value:
          type: string
        operator:
          description: "null"
          enum:
          - EQ
          - NEQ
          - LT
          - LTE
          - GT
          - GTE
          - BETWEEN
          - IN
          - NOT_IN
          - HAS_PROPERTY
          - NOT_HAS_PROPERTY
          - CONTAINS_TOKEN
          - NOT_CONTAINS_TOKEN
          type: string
      required:
      - operator
      - propertyName
      type: object
    BatchInputSimplePublicObjectBatchInput:
      example:
        inputs:
        - id: "1"
          properties:
            amount: "1500.00"
            dealname: Custom data integrations
            pipeline: default
            closedate: 2019-12-07T16:50:06.678Z
            dealstage: presentationscheduled
            hubspot_owner_id: "910901"
        - id: "1"
          properties:
            amount: "1500.00"
            dealname: Custom data integrations
            pipeline: default
            closedate: 2019-12-07T16:50:06.678Z
            dealstage: presentationscheduled
            hubspot_owner_id: "910901"
      properties:
        inputs:
          items:
            $ref: '#/components/schemas/SimplePublicObjectBatchInput'
          type: array
      required:
      - inputs
      type: object
    BatchInputSimplePublicObjectInputForCreate:
      example:
        inputs:
        - properties:
            amount: "1500.00"
            dealname: Custom data integrations
            pipeline: default
            closedate: 2019-12-07T16:50:06.678Z
            dealstage: presentationscheduled
            hubspot_owner_id: "910901"
          associations:
          - to:
              id: "101"
            types:
            - associationCategory: HUBSPOT_DEFINED
              associationTypeId: 2
        - properties:
            amount: "1500.00"
            dealname: Custom data integrations
            pipeline: default
            closedate: 2019-12-07T16:50:06.678Z
            dealstage: presentationscheduled
            hubspot_owner_id: "910901"
          associations:
          - to:
              id: "101"
            types:
            - associationCategory: HUBSPOT_DEFINED
              associationTypeId: 2
      properties:
        inputs:
          items:
            $ref: '#/components/schemas/SimplePublicObjectInputForCreate'
          type: array
      required:
      - inputs
      type: object
    PreviousPage:
      properties:
        before:
          type: string
        link:
          type: string
      required:
      - before
      type: object
    SimplePublicObjectBatchInput:
      example:
        id: "1"
        properties:
          amount: "1500.00"
          dealname: Custom data integrations
          pipeline: default
          closedate: 2019-12-07T16:50:06.678Z
          dealstage: presentationscheduled
          hubspot_owner_id: "910901"
      properties:
        idProperty:
          example: my_unique_property_name
          type: string
        id:
          type: string
        properties:
          additionalProperties:
            type: string
          example:
            amount: "1500.00"
            dealname: Custom data integrations
            pipeline: default
            closedate: 2019-12-07T16:50:06.678Z
            dealstage: presentationscheduled
            hubspot_owner_id: "910901"
          type: object
      required:
      - id
      - properties
      type: object
    AssociatedId:
      properties:
        id:
          type: string
        type:
          type: string
      required:
      - id
      - type
      type: object
    NextPage:
      example:
        after: NTI1Cg%3D%3D
        link: ?after=NTI1Cg%3D%3D
      properties:
        link:
          example: ?after=NTI1Cg%3D%3D
          type: string
        after:
          example: NTI1Cg%3D%3D
          type: string
      required:
      - after
      type: object
    SimplePublicObjectInputForCreate:
      example:
        properties:
          amount: "1500.00"
          dealname: Custom data integrations
          pipeline: default
          closedate: 2019-12-07T16:50:06.678Z
          dealstage: presentationscheduled
          hubspot_owner_id: "910901"
        associations:
        - to:
            id: "101"
          types:
          - associationCategory: HUBSPOT_DEFINED
            associationTypeId: 2
      properties:
        associations:
          items:
            $ref: '#/components/schemas/PublicAssociationsForObject'
          type: array
        properties:
          additionalProperties:
            type: string
          example:
            amount: "1500.00"
            dealname: Custom data integrations
            pipeline: default
            closedate: 2019-12-07T16:50:06.678Z
            dealstage: presentationscheduled
            hubspot_owner_id: "910901"
          type: object
      required:
      - associations
      - properties
      type: object
  securitySchemes:
    oauth2_legacy:
      flows:
        authorizationCode:
          authorizationUrl: https://app.hubspot.com/oauth/authorize
          scopes:
            media_bridge.read: Read media and media events
            crm.objects.goals.read: Read goals
            tickets: Read and write tickets
            crm.objects.custom.read: View custom object records
            e-commerce: e-commerce
            crm.objects.custom.write: Change custom object records
          tokenUrl: https://api.hubapi.com/oauth/v1/token
      type: oauth2
    oauth2:
      flows:
        authorizationCode:
          authorizationUrl: https://app.hubspot.com/oauth/authorize
          scopes:
            crm.objects.deals.read: ' '
            crm.objects.line_items.read: Line Items
            crm.objects.deals.write: ' '
            crm.objects.quotes.read: Quotes
            crm.objects.line_items.write: Line Items
            crm.objects.companies.read: ' '
            crm.objects.companies.write: ' '
            crm.objects.contacts.write: ' '
            crm.objects.contacts.read: ' '
            crm.objects.quotes.write: Quotes
          tokenUrl: https://api.hubapi.com/oauth/v1/token
      type: oauth2
    private_apps_legacy:
      in: header
      name: private-app-legacy
      type: apiKey
    private_apps:
      in: header
      name: private-app
      type: apiKey
x-hubspot-available-client-libraries:
- PHP
- Node
- Ruby
- Python
x-hubspot-product-tier-requirements:
  marketing: FREE
  sales: FREE
  service: FREE
  cms: FREE
x-hubspot-documentation-banner: NONE
