openapi: 3.0.1
info:
  description: "The CRM uses schemas to define how custom objects should store and\
    \ represent information in the HubSpot CRM. Schemas define details about an object's\
    \ type, properties, and associations. The schema can be uniquely identified by\
    \ its **object type ID**."
  title: Schemas
  version: v3
servers:
- url: https://api.hubapi.com/
tags:
- name: Core
- name: Public_Object_Schemas
paths:
  /crm/v3/schemas:
    get:
      description: Returns all object schemas that have been defined for your account.
      operationId: get-/crm-object-schemas/v3/schemas_getAll
      parameters:
      - description: Whether to return only results that have been archived.
        explode: true
        in: query
        name: archived
        required: false
        schema:
          default: false
          type: boolean
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CollectionResponseObjectSchemaNoPaging'
          description: successful operation
        default:
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Error'
          description: An error occurred.
      security:
      - oauth2_legacy:
        - crm.objects.custom.read
      - oauth2_legacy:
        - crm.schemas.custom.read
      summary: Get all schemas
      tags:
      - Core
    post:
      description: "Define a new object schema, along with custom properties and associations.\
        \ The entire object schema, including its object type ID, properties, and\
        \ associations will be returned in the response."
      operationId: post-/crm-object-schemas/v3/schemas_create
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ObjectSchemaEgg'
        description: "Object schema definition, including properties and associations."
        required: true
      responses:
        "201":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ObjectSchema'
          description: successful operation
        default:
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Error'
          description: An error occurred.
      security: []
      summary: Create a new schema
      tags:
      - Core
  /crm/v3/schemas/{objectType}:
    delete:
      description: Deletes a schema. Any existing records of this schema must be deleted
        **first**. Otherwise this call will fail.
      operationId: "delete-/crm-object-schemas/v3/schemas/{objectType}_archive"
      parameters:
      - description: Fully qualified name or object type ID of your schema.
        explode: false
        in: path
        name: objectType
        required: true
        schema:
          type: string
        style: simple
      - description: Whether to return only results that have been archived.
        explode: true
        in: query
        name: archived
        required: false
        schema:
          default: false
          type: boolean
        style: form
      responses:
        "204":
          content: {}
          description: No content
        default:
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Error'
          description: An error occurred.
      security: []
      summary: Delete a schema
      tags:
      - Core
    get:
      description: Returns an existing object schema.
      operationId: "get-/crm-object-schemas/v3/schemas/{objectType}_getById"
      parameters:
      - description: Fully qualified name or object type ID of your schema.
        explode: false
        in: path
        name: objectType
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ObjectSchema'
          description: successful operation
        default:
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Error'
          description: An error occurred.
      security:
      - oauth2_legacy:
        - crm.objects.custom.read
      - oauth2_legacy:
        - crm.schemas.custom.read
      summary: Get an existing schema
      tags:
      - Core
    patch:
      description: Update the details for an existing object schema.
      operationId: "patch-/crm-object-schemas/v3/schemas/{objectType}_update"
      parameters:
      - description: Fully qualified name or object type ID of your schema.
        explode: false
        in: path
        name: objectType
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ObjectTypeDefinitionPatch'
        description: Attributes to update in your schema.
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ObjectTypeDefinition'
          description: successful operation
        default:
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Error'
          description: An error occurred.
      security: []
      summary: Update a schema
      tags:
      - Core
  /crm/v3/schemas/{objectType}/associations:
    post:
      description: Defines a new association between the primary schema's object type
        and other object types.
      operationId: "post-/crm-object-schemas/v3/schemas/{objectType}/associations_createAssociation"
      parameters:
      - description: Fully qualified name or object type ID of your schema.
        explode: false
        in: path
        name: objectType
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AssociationDefinitionEgg'
        description: Attributes that define the association.
        required: true
      responses:
        "201":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AssociationDefinition'
          description: successful operation
        default:
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Error'
          description: An error occurred.
      security: []
      summary: Create an association
      tags:
      - Core
  /crm/v3/schemas/{objectType}/associations/{associationIdentifier}:
    delete:
      description: Removes an existing association from a schema.
      operationId: "delete-/crm-object-schemas/v3/schemas/{objectType}/associations/{associationIdentifier}_archiveAssociation"
      parameters:
      - description: Fully qualified name or object type ID of your schema.
        explode: false
        in: path
        name: objectType
        required: true
        schema:
          type: string
        style: simple
      - description: Unique ID of the association to remove.
        explode: false
        in: path
        name: associationIdentifier
        required: true
        schema:
          type: string
        style: simple
      responses:
        "204":
          content: {}
          description: No content
        default:
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Error'
          description: An error occurred.
      security: []
      summary: Remove an association
      tags:
      - Core
  /crm/v3/schemas/{objectType}/purge:
    delete:
      deprecated: true
      operationId: "delete-/crm-object-schemas/v3/schemas/{objectType}/purge_purge"
      parameters:
      - explode: false
        in: path
        name: objectType
        required: true
        schema:
          type: string
        style: simple
      responses:
        "204":
          content: {}
          description: No content
        default:
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Error'
          description: An error occurred.
      security: []
      tags:
      - Public_Object_Schemas
components:
  responses:
    Error:
      content:
        '*/*':
          schema:
            $ref: '#/components/schemas/Error'
      description: An error occurred.
  schemas:
    AssociationDefinition:
      description: Defines an association between two object types.
      example:
        id: "105"
        fromObjectTypeId: 2-123456
        toObjectTypeId: 0-1
        name: my_object_to_contact
      properties:
        fromObjectTypeId:
          description: ID of the primary object type to link from.
          type: string
        toObjectTypeId:
          description: ID of the target object type ID to link to.
          type: string
        name:
          description: A unique name for this association.
          type: string
        id:
          description: A unique ID for this association.
          type: string
        createdAt:
          description: When the association was defined.
          format: date-time
          type: string
        updatedAt:
          description: When the association was last updated.
          format: date-time
          type: string
      required:
      - fromObjectTypeId
      - id
      - toObjectTypeId
      type: object
    AssociationDefinitionEgg:
      description: Defines an association between two object types.
      example:
        fromObjectTypeId: 2-123456
        toObjectTypeId: contact
        name: my_object_to_contact
      properties:
        fromObjectTypeId:
          description: ID of the primary object type to link from.
          type: string
        toObjectTypeId:
          description: ID of the target object type ID to link to.
          type: string
        name:
          description: A unique name for this association.
          type: string
      required:
      - fromObjectTypeId
      - toObjectTypeId
      type: object
    CollectionResponseObjectSchemaNoPaging:
      example:
        results:
        - id: "123456"
          createdAt: 2020-02-20T18:07:11.390Z
          updatedAt: 2020-02-20T18:09:07.555Z
          properties:
          - updatedAt: 2020-02-20T18:07:11.802Z
            createdAt: 2020-02-20T18:07:11.802Z
            name: my_object_property
            label: My object property
            type: string
            fieldType: text
            groupName: my_object_information
            displayOrder: -1
            calculated: false
            externalOptions: false
            archived: false
            hasUniqueValue: false
          associations:
          - id: "123"
            fromObjectTypeId: 2-123456
            toObjectTypeId: 0-1
            name: my_object_to_contact
          labels:
            singular: My object
            plural: My objects
          requiredProperties:
          - my_object_property
          searchableProperties:
          - my_object_property
          primaryDisplayProperty: my_object_property
          metaType: PORTAL_SPECIFIC
          fullyQualifiedName: p7878787_my_object"
          name: my_object
        - id: "123456"
          createdAt: 2020-02-20T18:07:11.390Z
          updatedAt: 2020-02-20T18:09:07.555Z
          properties:
          - updatedAt: 2020-02-20T18:07:11.802Z
            createdAt: 2020-02-20T18:07:11.802Z
            name: my_object_property
            label: My object property
            type: string
            fieldType: text
            groupName: my_object_information
            displayOrder: -1
            calculated: false
            externalOptions: false
            archived: false
            hasUniqueValue: false
          associations:
          - id: "123"
            fromObjectTypeId: 2-123456
            toObjectTypeId: 0-1
            name: my_object_to_contact
          labels:
            singular: My object
            plural: My objects
          requiredProperties:
          - my_object_property
          searchableProperties:
          - my_object_property
          primaryDisplayProperty: my_object_property
          metaType: PORTAL_SPECIFIC
          fullyQualifiedName: p7878787_my_object"
          name: my_object
      properties:
        results:
          items:
            $ref: '#/components/schemas/ObjectSchema'
          type: array
      required:
      - results
      type: object
    Error:
      example:
        message: Invalid input (details will vary based on the error)
        correlationId: aeb5f871-7f07-4993-9211-075dc63e7cbf
        category: VALIDATION_ERROR
        links:
          knowledge-base: https://www.hubspot.com/products/service/knowledge-base
      properties:
        message:
          description: A human readable message describing the error along with remediation
            steps where appropriate
          example: An error occurred
          type: string
        correlationId:
          description: A unique identifier for the request. Include this value with
            any error reports or support tickets
          example: aeb5f871-7f07-4993-9211-075dc63e7cbf
          format: uuid
          type: string
        category:
          description: The error category
          type: string
        subCategory:
          description: A specific category that contains more specific detail about
            the error
          type: string
        errors:
          description: further information about the error
          items:
            $ref: '#/components/schemas/ErrorDetail'
          type: array
        context:
          additionalProperties:
            items:
              type: string
            type: array
          description: Context about the error condition
          example:
            invalidPropertyName:
            - propertyValue
            missingScopes:
            - scope1
            - scope2
          type: object
        links:
          additionalProperties:
            type: string
          description: A map of link names to associated URIs containing documentation
            about the error or recommended remediation steps
          type: object
      required:
      - category
      - correlationId
      - message
      type: object
    ErrorDetail:
      properties:
        message:
          description: A human readable message describing the error along with remediation
            steps where appropriate
          type: string
        in:
          description: The name of the field or parameter in which the error was found.
          type: string
        code:
          description: The status code associated with the error detail
          type: string
        subCategory:
          description: A specific category that contains more specific detail about
            the error
          type: string
        context:
          additionalProperties:
            items:
              type: string
            type: array
          description: Context about the error condition
          example:
            missingScopes:
            - scope1
            - scope2
          type: object
      required:
      - message
      type: object
    ObjectSchema:
      description: "Defines an object schema, including its properties and associations."
      example:
        id: "123456"
        createdAt: 2020-02-20T18:07:11.390Z
        updatedAt: 2020-02-20T18:09:07.555Z
        properties:
        - updatedAt: 2020-02-20T18:07:11.802Z
          createdAt: 2020-02-20T18:07:11.802Z
          name: my_object_property
          label: My object property
          type: string
          fieldType: text
          groupName: my_object_information
          displayOrder: -1
          calculated: false
          externalOptions: false
          archived: false
          hasUniqueValue: false
        associations:
        - id: "123"
          fromObjectTypeId: 2-123456
          toObjectTypeId: 0-1
          name: my_object_to_contact
        labels:
          singular: My object
          plural: My objects
        requiredProperties:
        - my_object_property
        searchableProperties:
        - my_object_property
        primaryDisplayProperty: my_object_property
        metaType: PORTAL_SPECIFIC
        fullyQualifiedName: p7878787_my_object"
        name: my_object
      properties:
        labels:
          $ref: '#/components/schemas/ObjectTypeDefinitionLabels'
        requiredProperties:
          description: The names of properties that should be **required** when creating
            an object of this type.
          items:
            type: string
          type: array
        searchableProperties:
          description: Names of properties that will be indexed for this object type
            in by HubSpot's product search.
          items:
            type: string
          type: array
        primaryDisplayProperty:
          description: The name of the primary property for this object. This will
            be displayed as primary on the HubSpot record page for this object type.
          type: string
        secondaryDisplayProperties:
          description: The names of secondary properties for this object. These will
            be displayed as secondary on the HubSpot record page for this object type.
          items:
            type: string
          type: array
        archived:
          type: boolean
        id:
          description: "A unique ID for this schema's object type. Will be defined\
            \ as {meta-type}-{unique ID}."
          type: string
        fullyQualifiedName:
          description: "An assigned unique ID for the object, including portal ID\
            \ and object name."
          type: string
        createdAt:
          description: When the object schema was created.
          format: date-time
          type: string
        updatedAt:
          description: When the object schema was last updated.
          format: date-time
          type: string
        objectTypeId:
          type: string
        properties:
          description: Properties defined for this object type.
          items:
            $ref: '#/components/schemas/Property'
          type: array
        associations:
          description: Associations defined for a given object type.
          items:
            $ref: '#/components/schemas/AssociationDefinition'
          type: array
        name:
          description: A unique name for the schema's object type.
          type: string
      required:
      - archived
      - associations
      - fullyQualifiedName
      - id
      - labels
      - name
      - objectTypeId
      - properties
      - requiredProperties
      - searchableProperties
      - secondaryDisplayProperties
      type: object
    ObjectSchemaEgg:
      description: "Defines a new object type, its properties, and associations."
      example:
        name: my_object
        labels:
          singular: My object
          plural: My objects
        primaryDisplayProperty: my_object_property
        requiredProperties:
        - my_object_property
        properties:
        - name: my_object_property
          label: My object property
          isPrimaryDisplayLabel: true
        associatedObjects:
        - CONTACT
        metaType: PORTAL_SPECIFIC
      properties:
        labels:
          $ref: '#/components/schemas/ObjectTypeDefinitionLabels'
        requiredProperties:
          description: The names of properties that should be **required** when creating
            an object of this type.
          items:
            type: string
          type: array
        searchableProperties:
          description: Names of properties that will be indexed for this object type
            in by HubSpot's product search.
          items:
            type: string
          type: array
        primaryDisplayProperty:
          description: The name of the primary property for this object. This will
            be displayed as primary on the HubSpot record page for this object type.
          type: string
        secondaryDisplayProperties:
          description: The names of secondary properties for this object. These will
            be displayed as secondary on the HubSpot record page for this object type.
          items:
            type: string
          type: array
        properties:
          description: Properties defined for this object type.
          items:
            $ref: '#/components/schemas/ObjectTypePropertyCreate'
          type: array
        associatedObjects:
          description: Associations defined for this object type.
          items:
            type: string
          type: array
        name:
          description: A unique name for this object. For internal use only.
          type: string
      required:
      - associatedObjects
      - labels
      - name
      - properties
      - requiredProperties
      - searchableProperties
      - secondaryDisplayProperties
      type: object
    ObjectTypeDefinition:
      description: Defines an object type.
      example:
        id: "123456"
        createdAt: 2020-02-20T18:07:11.390Z
        updatedAt: 2020-02-21T14:13:28.818002Z
        labels:
          singular: My object
          plural: My objects
        requiredProperties:
        - my_object_property
        searchableProperties:
        - my_object_property
        primaryDisplayProperty: my_object_property
        portalId: 12345678
        metaType: PORTAL_SPECIFIC
        name: my_object
      properties:
        labels:
          $ref: '#/components/schemas/ObjectTypeDefinitionLabels'
        requiredProperties:
          description: The names of properties that should be **required** when creating
            an object of this type.
          items:
            type: string
          type: array
        searchableProperties:
          description: Names of properties that will be indexed for this object type
            in by HubSpot's product search.
          items:
            type: string
          type: array
        primaryDisplayProperty:
          description: The name of the primary property for this object. This will
            be displayed as primary on the HubSpot record page for this object type.
          type: string
        secondaryDisplayProperties:
          description: The names of secondary properties for this object. These will
            be displayed as secondary on the HubSpot record page for this object type.
          items:
            type: string
          type: array
        archived:
          type: boolean
        id:
          description: "A unique ID for this object type. Will be defined as {meta-type}-{unique\
            \ ID}."
          type: string
        fullyQualifiedName:
          type: string
        createdAt:
          description: When the object type was created.
          format: date-time
          type: string
        updatedAt:
          description: When the object type was last updated.
          format: date-time
          type: string
        objectTypeId:
          type: string
        name:
          description: A unique name for this object. For internal use only.
          type: string
        portalId:
          description: The ID of the account that this object type is specific to.
          format: int32
          type: integer
      required:
      - archived
      - fullyQualifiedName
      - id
      - labels
      - name
      - objectTypeId
      - requiredProperties
      - searchableProperties
      - secondaryDisplayProperties
      type: object
    ObjectTypeDefinitionLabels:
      description: Singular and plural labels for the object. Used in CRM display.
      example:
        singular: My object
        plural: My objects
      properties:
        singular:
          description: The word for one object. (There’s no way to change this later.)
          type: string
        plural:
          description: The word for multiple objects. (There’s no way to change this
            later.)
          type: string
      type: object
    ObjectTypeDefinitionPatch:
      description: Defines attributes to update on an object type.
      example:
        primaryDisplayProperty: my_object_property
        requiredProperties:
        - my_object_property
        searchableProperties:
        - my_object_property
      properties:
        labels:
          $ref: '#/components/schemas/ObjectTypeDefinitionLabels'
        requiredProperties:
          description: The names of properties that should be **required** when creating
            an object of this type.
          items:
            type: string
          type: array
        searchableProperties:
          description: Names of properties that will be indexed for this object type
            in by HubSpot's product search.
          items:
            type: string
          type: array
        primaryDisplayProperty:
          description: The name of the primary property for this object. This will
            be displayed as primary on the HubSpot record page for this object type.
          type: string
        secondaryDisplayProperties:
          description: The names of secondary properties for this object. These will
            be displayed as secondary on the HubSpot record page for this object type.
          items:
            type: string
          type: array
        restorable:
          type: boolean
      type: object
    ObjectTypePropertyCreate:
      description: Defines a property to create.
      example:
        label: My object property
        type: enumeration
        fieldType: select
        groupName: my_object_information
        displayOrder: 2
        hasUniqueValue: false
        options:
        - label: Option A
          description: Choice number one
          value: A
          displayOrder: 1
        - label: Option B
          description: Choice number two
          value: B
          displayOrder: 2
      properties:
        name:
          description: "The internal property name, which must be used when referencing\
            \ the property from the API."
          type: string
        label:
          description: A human-readable property label that will be shown in HubSpot.
          type: string
        groupName:
          description: The name of the group this property belongs to.
          type: string
        description:
          description: A description of the property that will be shown as help text
            in HubSpot.
          type: string
        options:
          description: A list of available options for the property. This field is
            only required for enumerated properties.
          items:
            $ref: '#/components/schemas/OptionInput'
          type: array
        displayOrder:
          description: The order that this property should be displayed in the HubSpot
            UI relative to other properties for this object type. Properties are displayed
            in order starting with the lowest positive integer value. A value of -1
            will cause the property to be displayed **after** any positive values.
          format: int32
          type: integer
        hasUniqueValue:
          description: "Whether or not the property's value must be unique. Once set,\
            \ this can't be changed."
          type: boolean
        hidden:
          type: boolean
        type:
          description: The data type of the property.
          enum:
          - string
          - number
          - date
          - datetime
          - enumeration
          - bool
          type: string
        fieldType:
          description: Controls how the property appears in HubSpot.
          type: string
      required:
      - fieldType
      - label
      - name
      - type
      type: object
    Option:
      description: The options available when a property is an enumeration
      example:
        label: Option A
        description: Choice number one
        value: A
        displayOrder: 1
        hidden: false
      properties:
        label:
          description: A human-readable option label that will be shown in HubSpot.
          type: string
        value:
          description: "The internal value of the option, which must be used when\
            \ setting the property value through the API."
          type: string
        description:
          description: A description of the option.
          type: string
        displayOrder:
          description: Options are displayed in order starting with the lowest positive
            integer value. Values of -1 will cause the option to be displayed after
            any positive values.
          format: int32
          type: integer
        hidden:
          description: Hidden options will not be displayed in HubSpot.
          type: boolean
      required:
      - hidden
      - label
      - value
      type: object
    OptionInput:
      description: Defines a enumeration property option
      example:
        label: Option A
        description: Choice number one
        value: A
        displayOrder: 1
        hidden: false
      properties:
        label:
          description: A human-readable option label that will be shown in HubSpot.
          type: string
        value:
          description: "The internal value of the option, which must be used when\
            \ setting the property value through the API."
          type: string
        description:
          description: A description of the option.
          type: string
        displayOrder:
          description: Options are shown in order starting with the lowest positive
            integer value. Values of -1 will cause the option to be displayed after
            any positive values.
          format: int32
          type: integer
        hidden:
          description: Hidden options won't be shown in HubSpot.
          type: boolean
      required:
      - displayOrder
      - hidden
      - label
      - value
      type: object
    Property:
      description: Defines a property
      example:
        name: my_object_property
        label: My object property
        type: enumeration
        fieldType: select
        groupName: my_object_information
        displayOrder: 2
        hasUniqueValue: false
        modificationMetadata:
          readOnlyOptions: false
          readOnlyValue: false
          readOnlyDefinition: false
          archivable: true
        options:
        - label: Option A
          description: Choice number one
          value: A
          displayOrder: 1
          hidden: false
        - label: Option B
          description: Choice number two
          value: B
          displayOrder: 2
          hidden: false
      properties:
        updatedAt:
          format: date-time
          type: string
        createdAt:
          description: When the property was created
          format: date-time
          type: string
        archivedAt:
          description: When the property was archived.
          format: date-time
          type: string
        name:
          description: "The internal property name, which must be used when referencing\
            \ the property via the API."
          type: string
        label:
          description: A human-readable property label that will be shown in HubSpot.
          type: string
        type:
          description: The property data type.
          type: string
        fieldType:
          description: Controls how the property appears in HubSpot.
          type: string
        description:
          description: A description of the property that will be shown as help text
            in HubSpot.
          type: string
        groupName:
          description: The name of the property group the property belongs to.
          type: string
        options:
          description: "A list of valid options for the property. This field is required\
            \ for enumerated properties, but will be empty for other property types."
          items:
            $ref: '#/components/schemas/Option'
          type: array
        createdUserId:
          description: The internal ID of the user who created the property in HubSpot.
            This field may not exist if the property was created outside of HubSpot.
          type: string
        updatedUserId:
          description: The internal user ID of the user who updated the property in
            HubSpot. This field may not exist if the property was updated outside
            of HubSpot.
          type: string
        referencedObjectType:
          description: "If this property is related to other object(s), they'll be\
            \ listed here."
          type: string
        displayOrder:
          description: The order that this property should be displayed in the HubSpot
            UI relative to other properties for this object type. Properties are displayed
            in order starting with the lowest positive integer value. A value of -1
            will cause the property to be displayed **after** any positive values.
          format: int32
          type: integer
        calculated:
          description: "For default properties, true indicates that the property is\
            \ calculated by a HubSpot process. It has no effect for custom properties."
          type: boolean
        externalOptions:
          description: "For default properties, true indicates that the options are\
            \ stored externally to the property settings."
          type: boolean
        archived:
          description: Whether or not the property is archived.
          type: boolean
        hasUniqueValue:
          description: "Whether or not the property's value must be unique. Once set,\
            \ this can't be changed."
          type: boolean
        hidden:
          type: boolean
        hubspotDefined:
          description: This will be true for default object properties built into
            HubSpot.
          type: boolean
        showCurrencySymbol:
          description: Whether the property will display the currency symbol set in
            the account settings.
          type: boolean
        modificationMetadata:
          $ref: '#/components/schemas/PropertyModificationMetadata'
        formField:
          description: Whether or not the property can be used in a HubSpot form.
          type: boolean
      required:
      - description
      - fieldType
      - groupName
      - label
      - name
      - options
      - type
      type: object
    PropertyModificationMetadata:
      properties:
        archivable:
          type: boolean
        readOnlyDefinition:
          type: boolean
        readOnlyOptions:
          type: boolean
        readOnlyValue:
          type: boolean
      required:
      - archivable
      - readOnlyDefinition
      - readOnlyValue
      type: object
  securitySchemes:
    oauth2_legacy:
      flows:
        authorizationCode:
          authorizationUrl: https://app.hubspot.com/oauth/authorize
          scopes:
            crm.schemas.custom.read: View custom object definitions
            crm.objects.custom.read: View custom object records
          tokenUrl: https://api.hubapi.com/oauth/v1/token
      type: oauth2
x-hubspot-available-client-libraries:
- PHP
- Node
- Python
- Ruby
